# frozen_string_literal: true

source "https://rubygems.org"

# sinatra
gem "sinatra", "~> 2.0"
gem "sinatra-contrib", "~> 2.0"

# gem "rails"
gem "puma", "~> 5.0"
gem "pg", "~> 1.0"
gem "activerecord", "~> 6.0"
gem "sinatra-activerecord", "~> 2.0"
